### ISSUE TITLE
Croparia 1.18.1 MC 1.12.2 Still Crash Issues

### ISSUE THREAD

**Issue by TheOrionsun** [PowerInMC/Croparia#8]
Hello,

Tested again Croparia 1.18.1 MC 1.12.2 with release version of Industrial Craft 2-2.8.73-ex112 and still crashes on loading.

Using Twitch custom profile with just these two mods and Forge-14.23.4.2705.

---- Minecraft Crash Report ----
// Don't do that.

Time: 7/2/18 8:03 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281027568 bytes (268 MB) / 1657274368 bytes (1580 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID        | Version      | Source                             | Signature                                |
	|:------- |:--------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJA  | mcp       | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJA  | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge     | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | croparia  | 1.18         | Croparia-1.18.1.jar                | None                                     |
	| UCHIJA  | ic2       | 2.8.73-ex112 | industrialcraft-2-2.8.73-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1080/PCIe/SSE2'

**Comment by TheOrionsun** [comment]
Hello,

I updated Industrial to newest Bata and checked the Croparia config for the use of Bonemeal and it is set to true.

MC load still crashes:

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/3/18 4:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079)
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 549499344 bytes (524 MB) / 1661992960 bytes (1585 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID        | Version      | Source                             | Signature                                |
	|:------- |:--------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJA  | mcp       | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJA  | FML       | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAE | forge     | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | croparia  | 1.18         | Croparia-1.18.1.jar                | None                                     |
	| UCHIJA  | ic2       | 2.8.90-ex112 | industrialcraft-2-2.8.90-ex112.jar | de041f9f6187debbc77034a344134053277aa3b0 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.36' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
